version: "3.3"
services:

  pathfinder:
    image: eqlabs/pathfinder:v0.2.6-alpha
    ports:
      - 9545
    environment:
      - RUST_LOG=info
      - PATHFINDER_ETHEREUM_API_URL=${ALCHEMY_KEY}
    deploy:
      mode: replicated
      replicas: 8
      restart_policy:
        condition: on-failure
